### ISSUE TITLE
Access control page - unable to assign special access - prod and test

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#141]
### Descriptive summary
Attempting to assign special access to an individual user from an item's access control page results in a "sorry something went wrong" error. Assigning individual access to items is a requirement of one group of ERA A+V users

### Expected behaviour
Special access can be granted to individual users

### Steps to reproduce the behaviour

1. Go to any item's access control page and assign special access to an ERA A+V users (CCID@ualberta.ca)

**Comment by seanluyk** [comment]
It appears that this is a collection specific problem (Grant Assist Program NSERC)

**Comment by cwant** [comment]
Reproduced with visiting an item in the collection and switching permissions from 'Collection staff' to 'Logged in users'.

**Comment by cwant** [comment]
Hi Sean,

This problem seems to have gone away. I was able to assign myself as a manager on this page:

https://era-av.library.ualberta.ca/admin/collections/avalon:1151

Can you confirm that this problem still exists?

If the problem has indeed gone away, it indicates an issue with the deployment.

**Comment by seanluyk** [comment]
Hi @cwant , it seems to have resolved itself at the collection level page, but try an object, e.g. https://era-av.library.ualberta.ca/media_objects/avalon:1163/edit

**Comment by cwant** [comment]
Hi @seanluyk 
I can reproduce this, and thanks to my recent access to production logs, I've found the root cause: the update to the media object fails because it doesn't have a 'Genre' associated to it (this is now a required field). So something that looks like a permission issue is caused by something unrelated. Will continue to poke around at options, but the two most sensible ones seem to be:

1) Fail gracefully, and mention that a genre is required for the item;
2) Don't validate descriptive metadata on access control update.

**Comment by cwant** [comment]
I will also write a little script for @taichun to run to identify invalid items in our production instance so that we can correct them now rather than suffer surprises later.

**Comment by cwant** [comment]
The audit identified several invalid media objects, and that work is in #153, and waiting action from the metadata team.

The next step for this issue is to figure out why these activities are throwing errors rather than gracefully providing the user with a usable error message.

**Comment by seanluyk** [comment]
Doing some cleanup
