### ISSUE TITLE
Search engines fill Solr log

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#171]
As reported to @taichun .
Yandex is the most aggresive for frequently crawling the website.
We need to review policy about how our collection is indexed.

**Comment by cwant** [comment]
@taichun with your changes to robot.txt earlier this week, does this mean that the problem described in this ticket is now fixed?

**Comment by taichun** [comment]
Until next release. Please incorporate the updated robots.txt per UAL
websites policy in the next release.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by cwant** [comment]
@taichun Huh? What updated robots.txt? And do you have a link to the policy?

**Comment by cwant** [comment]
@weiweishi this is the ERA robots.txt:

https://github.com/ualbertalib/HydraNorth/blob/master/public/robots.txt

Do you feel that this is the way to go for Avalon? (And sufficient to solve the problem described in this issue?)

**Comment by weiweishi** [comment]
I think part of this issue was caused by crawlers follow every single facet
links.  And blocking /catalog should help with the situation.  I'm not sure
if it will solve the issue entirely. One thing to consider is to create a
sitemap for ERA-AV? But I think this could be the first step.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by seanluyk** [comment]
Would this be considered unfriendly crawling? If so, could we not just block that domain entierly from crawling?

**Comment by cwant** [comment]
If Yandex is the only one causing issues, we could include:

User-agent: Yandex
Disallow: /catalog

(For now, until we have a proper site map.)

**Comment by seanluyk** [comment]
Can we just let them know that there's no Trump intelligence on ERA A+V so they'll back off? ;)

**Comment by cwant** [comment]
As discussed at the grooming meeting, we'll put in the Yandex rule now, and move the sitemap portion of this issue to #184.
