### ISSUE TITLE
Avalon logo on mobile device

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#18]
When ERA Audio+Video main page is opened on a mobile device it shows an Avalon logo which needs to be suppressed.

**Comment by umarqasim** [comment]
validate after the new 5.1.4 release is in place

**Comment by cwant** [comment]
Note that this avalon logo is the header of the main application menu, which gets exposed when you click on the menu button, as shown in this screen shot:

![mobile_avalon_logo](https://cloud.githubusercontent.com/assets/672104/22761844/c8eae076-ee19-11e6-9514-d042d3aa899e.png)

I don't think the menu should go away, so then the question is what should replace the logo? It could be our own logo, or something simple like the text "Main menu".

**Comment by seanluyk** [comment]
I like Main Menu. Also, the ERA A+V logo could be much smaller as it's cutting off the University of Alberta Libraries logo. Would you like this in a separate issue @cwant?

**Comment by cwant** [comment]
Ugh, yeah, I didn't notice that. I think I recall reading something about it in Matt's "UI Papercuts" issue. I suppose it should be a separate issue, although it might be solved by the solution to this issue.

Another option that would fix both problems would be to make a light version of the ERA-AV logo and put it where the Avalon logo currently is (that is to say, get rid of the big ERA logo altogether on mobile, since it would be replaced by the smaller logo next to the menu).

We can test out both a version with 'Main menu' and one with smaller logo to see what works better.

**Comment by seanluyk** [comment]
I'm partial to the other option- I don't think we need to waste so much space with large logos, but yes, let's have a look at both options.

**Comment by cwant** [comment]
Here's a couple of mockups, showing the effect of open and closed menu in each case:

1) Smaller logo at top, 'Main Menu' in the bar with the menu:

![mobile_menu_main_menu](https://cloud.githubusercontent.com/assets/672104/22835648/acecaf22-ef76-11e6-965b-4854ad51f219.png)

2) No logo at top, smaller logo appears in the bar with the menu:

![mobile_menu_era_logo](https://cloud.githubusercontent.com/assets/672104/22835675/c8292af4-ef76-11e6-982d-e3ca8c37b22a.png)

(Please note that I hacked together the smaller logo, Natasha can make a proper one when she returns).

The U of A logo is fixed in both mockups.

**Comment by seanluyk** [comment]
I think option 2 looks better, it's a little more compact. Main menu is implied by the placement at the top anyway.

**Comment by nnunn** [comment]
closed. Although, it would be nice to get opinions on the direction I took this as it is different then the suggestions above. Basically, I have removed the main menu -- there are so few navigation options that we didn't seem to need it on the mobile view.
