### ISSUE TITLE
Investigate LTI errors in rollbar

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#191]
See attached:
[lti_errors.pdf](https://github.com/ualbertalib/avalon/files/1188575/lti_errors.pdf)
![lti_errors](https://user-images.githubusercontent.com/14880206/28793841-93d0fab4-75f1-11e7-901b-4c1a458fc9ed.png)

**Comment by cwant** [comment]
This one is tricky because Avalon 5.x uses a piece of Rack middleware to do stream authentication (at least that's what I think it's doing):

https://github.com/ualbertalib/avalon/blob/master/config.ru#L5
https://github.com/ualbertalib/avalon/blob/master/lib/avalon/stream_auth.rb#L22

When OAuth throws an error, it traces back to stream_auth#call, but stream_auth can't catch the error and do some kind of reasonable damage control (I don't know why -- a rescue block there is ineffective). The only hope of catching this one is to fork OAuth,

Avalon 6 has moved away from this setup, so I suspect the problem will go away when we upgrade.

**Comment by seanluyk** [comment]
Doing some cleanup
