### ISSUE TITLE
Avalon Version upgrade

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#20]
Upgrade to the most current Avalon version 5.1.4
https://github.com/avalonmediasystem/avalon/tree/v5.1.4

**Comment by cwant** [comment]
Status update: currently deployed on test.

One additional consideration I've been thinking about: since rebasing against an upstream branch is a somewhat destructive operation, we might want to take this opportunity to correct the authorship of some previous commits that are attributed to non-humans. In particular we have the authors:

Deployment Account <deploy@avtest01.library.ualberta.ca>
avalon <avalon@avalon-dev.library.ualberta.ca>
<root@avalon-dev.library.ualberta.ca>

These can be viewed here: https://github.com/ualbertalib/avalon/commits/master.

**Comment by weiweishi** [comment]
Agreed.
Would you like me to do the changes, or if I can give you the history of
the commits, you'd be able to help cleaning up this mess?

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by cwant** [comment]
Hi Weiwei,

I am guessing that all of the commits from July 20, 2017 onward (12 commits attributed to deploy, avalon and root) can be attributed to you.

There are three others from July 12th, 2016 (avalon, deploy) for whom the authorship is uncertain. In particular:

* Omniauth/Shibboleth:
   https://github.com/ualbertalib/avalon/commit/8ad6a49f90434c05e31486f78b19d26f75f96c87

* Add Wowza: 
   https://github.com/ualbertalib/avalon/commit/7e7a56183d07ae534929d07d476b86f811c0c8c0

* Use MySQL2 instead of SQLite3:
   https://github.com/ualbertalib/avalon/commit/e88552139cf94bcb6247193e29da273557c0cebb

Chris

**Comment by weiweishi** [comment]
I believe all these three belong to David. His email was
ddeschen@ualberta.ca

Thank you!

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
pending @umarqasim testing on batch ingest and UI.

**Comment by cwant** [comment]
@umarqasim & @seanluyk: this one is blocking a bunch of other work, so I am eager to roll it out ASAP.

It is deployed on the test server now. Let me know if you see any showstoppers. I don't anticipate any.

Cheers,
Chris

**Comment by seanluyk** [comment]
Not sure if these are because it's the test environment, but:
-I'm not able to successfully get an item to play - all videos appear to have zero minutes
-Could not add item to playlist. Error: "Item was not created: Couldn't find MasterFile without an ID"

**Comment by cwant** [comment]
Hi Sean,

Which particular item are you trying to access? (URL please.) I don't seem
to have this problem.

Chris

**Comment by seanluyk** [comment]
Here is one example: https://avalon-test.library.ualberta.ca/media_objects/avalon:35

**Comment by cwant** [comment]
Hi Seam,

I am unable to replicate here (Chrome, Linux). The movie shows a duration
of 15:11 and I am able to play it and add it to a playlist.
I am logged in as avalontest@library.ualberta.ca.

Chris

**Comment by weiweishi** [comment]
I was able to play it too with my own account. Sean, could you please try
again. I wonder if you were caught in between Tai-chun's ruby version
upgrade and server restarts etc.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by seanluyk** [comment]
Weird, I wonder if this has something to do with the fact I'm accessing from Rutherford? For example [this object](https://avalon-test.library.ualberta.ca/media_objects/avalon:35) I don't get playback and the timeline shows as 00:00: 
![image](https://cloud.githubusercontent.com/assets/14880206/22597854/8b12414c-e9ee-11e6-99ad-a60f752abe69.png)

**Comment by cwant** [comment]
That is an interesting observation, and could very well explain the issues you are seeing.

@taichun (I know you are away today): Sean appears to be connecting from 142.244.34.84, could you check if the test streaming server allows connections from that address (or from the LAN it is on).

**Comment by umarqasim** [comment]
@seanluyk can you edit this object? Can you try again, I have just made it public.

**Comment by seanluyk** [comment]
No problems editing the object before - it's just the playback and playlist issue (with all objects in TEST)

**Comment by cwant** [comment]
Committed to master branch. Not deployed in a release yet.

**Comment by cwant** [comment]
Deployed in release 5.1.5.20170201.uofa, closing ticket.
