### ISSUE TITLE
Fix the security warnings on Gemnasium

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#22]
To fix the outstanding security warnings on the master branch. 

@cwant I have a branch "version_upgrade" with the necessary gem upgrades, but not fully tested with our monkeypatches.

**Comment by umarqasim** [comment]
Meet with Ray and evaluate if we can wait until release 6.

**Comment by cwant** [comment]
I have done a rails 4.2 upgrade on a local branch, based on the Avalon v5.1.5 update branch. Uploaded a video, things seem to work. The test suite does not produce any additional errors than what was there before.

This issue is currently blocked by Issue #20 (Avalon version upgrade), which needs to be deployed before this work can be rolled out.

**Comment by weiweishi** [comment]
great news. thanks Chris.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by cwant** [comment]
Committed to master, not deployed in a release yet.

**Comment by cwant** [comment]
Deployed in release, and gemnasium lists zero issues now:

https://gemnasium.com/github.com/ualbertalib/avalon

Closing ticket.
