### ISSUE TITLE
Displaying dim video on Mac when using Safari

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#247]
### Descriptive summary

All videos are displaying dim when using Safari on a Mac. It is working fine on iPhone safari app.

### Expected behavior
The picture brightness should be normal on all platforms and browsers

### Steps to reproduce the behavior

Stream a video on a mac using safari browser

**Comment by cwant** [comment]
I've rolled back the test stack to the release just before the new design was implemented, and the problem goes away. I suspect there is either some CSS or javascript that got broken during the reskinning. Still investigation ...

**Comment by cwant** [comment]
Interesting findings:

* It looks like the style that is intended to make the homepage background videos faded is causing the issue here. Easy fix (although I'm not entirely sure why it only effects safari).

* One other thing I noticed is that the background videos on the homepage don't show up on safari. This likely is due to the encoding formats used, and we'll need to have another version of the videos to make them work with safari. I'll create a ticket for this and catch up with Natasha when she returns to work later in the week.

**Comment by seanluyk** [comment]
Thanks for investigating, @cwant, very weird that this style only affects Safari!

**Comment by umarqasim** [comment]
Great, thanks for figuring this out. Hope the fix will be in soon.

*--*
*Umar Qasim, PhD*
Digital Preservation Officer
2-10N Cameron Library | University of Alberta
Edmonton, Alberta T6G 2J8, Canada
Tel: 780-492-9861 | Fax: 780-492-9243
umar.qasim@ualberta.ca | http://www.umarqasim.ca
