### ISSUE TITLE
Revive test suites on Avalon

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#25]
Make sure the test suites for Avalon can be run properly on dev machines.

**Comment by weiweishi** [comment]
- [ ] Remaining issues with local validation with language and geographic/temporal subjects

**Comment by cwant** [comment]
Current status of this issue:

* This sprint the tests related to batch ingest were fixed. The problems were caused by the mock data from upstream avalon not including some of our required fields (language, topical subject), so the data from ingestion would fail validation during the tests. Updating the mock data fixes 13 of the 27 failing tests.
* The remaining 14 failing tests can be broken down into three groups:
  * API tests that fail because avalon doesn't handle language correctly;
  * An ordering dependency problem between some tests. This problem has been exposed because our tests seem to run in a different order than upstream (likely due to running different rails versions);
  * View tests that are expecting content related to the upstream avalon on our pages (e.g., the avalon version, link to avalon home page, etc).

Separate issues will be created for these three classes of failures, and this issue will be closed.
