### ISSUE TITLE
Changing LTI Integration Behavoir

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#37]
Currently when you open an lti integrated content, the full ERA Audio+Video Avalon page appears. Can we suppress the page to just open the video in full screen mode or just the player.

**Comment by cwant** [comment]
A demo of a solution for this is on the test server now:

Add option in eClass so that an instructor can enter into the
'Custom Parameters' for the added content the key/value
"embed_section=true". This will allow the video to be embedded into
the iframe in eClass rather than the whole page being loaded.
Note that this only works for a 'section' LTI URL from avalon,
not a 'item' LTI URL.

Or in step form:

1) In avalon, click the "share" link. Copy the 'section' LTI link instead of the 'item' LTI link (items are playlists and need additional content from the avalon website instead of just the player);
2) In eClass, add an item as usual, but in the 'Custom parameters" field, put in "embed_section=true". This will flag avalon to redirect to the URL with the movie clip for the section using an embedded player.

**Comment by seanluyk** [comment]
@umarqasim and Sean to try this solution out

**Comment by cwant** [comment]
Please test.

**Comment by umarqasim** [comment]
This solution seems to be working fine. We can close the ticket.

**Comment by seanluyk** [comment]
I don't think this one is completely resolved. It's not possible to correctly full screen a video using this method, except if Launch container = Existing window is selected. That works fine but then the browser back button won't bring you back to the course.

**Comment by cwant** [comment]
I'm not sure this is one we can overcome since the content is in an iframe, so I don't think it's possible to extend content outside of it. Apparently there is an option to permit an iFrame to allow fullscreen content, but this would be a setting on the Moodle side, and I don't think this can be turned:

http://stackoverflow.com/questions/27723423/youtube-iframe-embed-full-screen

**Comment by seanluyk** [comment]
Umar and I tested - choosing existing or external window gives acceptable results. Re-closing
