### ISSUE TITLE
[Avalon] Links redirection from ERA A+V Avalon 5 to Avalon 6

### ISSUE THREAD

**Issue by anayram** [ualbertalib/avalon#499]
### Descriptive summary
@sfarnel reminded me to check if links to ERA A+V on Avalon 5 will be redirected to Avalon 6.

I am working on reports of linking created within UAL resources in this ticket: ualbertalib/metadata#456

It is not a large amount of links but of course, there might be external resources either linking or embeding ERA A+V objects.

We have:
40 links within Avalon
41 links from UAL catalogue
12 links from Jupiter (checked isVersionOf, source, and relation fields)

If this something that  has already been sorted out please close ticket .

### Expected behavior
@pbinkley @umar @jefferya - which option would be better?

1. Redirect links to ERA A+V Avalon 5 to Avalon 6
2. Update links in ERA, ERA A+V, and UAL catalogue (this wouldn't help with external linking.)

**Comment by umarqasim** [comment]
Thanks for bringing this into our attention. Peter and I just discussed
this issue. Since there are a small number of items in the Catalog &
Jupiter(users may have bookmarks too though), we agreed to go ahead with
the upgrade and handle this after the upgrade. We can look into this during
the next sprint.

*--*
*Umar Qasim, PhD*
Digital Preservation Officer
2-10N Cameron Library | University of Alberta
Edmonton, Alberta T6G 2J8, Canada
Tel: 780-492-9861 | Fax: 780-492-9243
umar.qasim@ualberta.ca | http://www.umarqasim.ca

**Comment by anayram** [comment]
Thanks, @umarqasim !

**Comment by jefferya** [comment]
Closing because upstream added code to "Redirect v4-style PIDs to v6 pids."
* https://github.com/ualbertalib/avalon/commit/87fee337fd36488083416f450d25d8e2ae8c754a
* https://github.com/ualbertalib/avalon/blob/41a633c96271ea147b95f96a648a85423a01e0fc/app/controllers/application_controller.rb#L39-L46
