### ISSUE TITLE
Change page title to "ERA A+V"

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#541]
### Descriptive summary
Page title currently displays as "ERA_A+V"
![image](https://user-images.githubusercontent.com/14880206/64053651-7737c580-cb40-11e9-8ab9-df50d1a23c99.png)

### Expected behavior
Page title displays as "ERA A+V"

### Additional Context
Apologies for submitting a such a nitpicky issue about a single underscore :)

**Comment by taichun** [comment]
This variable is currently in the environment variables sourced by httpd
and due to it's configuration file format limitation we have to add the
underscore to eliminate the space.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by seanluyk** [comment]
@taichun, thanks for the explanation. Was this limitation added to Avalon 6? If it's possible to overcome, I would like this to change. If it's impossible, it will be good to know!

**Comment by jefferya** [comment]
Proposed solution given Tai-chun's finding: change the settings file in UAL repository

1. change `name` in settings.yml
https://github.com/ualbertalib/avalon/blob/avalon-6/config/settings.yml#L1

2. Once #1 is in production, for Tai-chun: remove environment variable: `SETTINGS__NAME` from
  - /etc/sysconfig/avalon6_env
  - /etc/httpd/conf/avalon6_env.conf

**Comment by weiweishi** [comment]
in production now
