### ISSUE TITLE
[SPIKE] Investigation on why values in the Genre field are converted to lowercase upon submission of the resource description form

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#559]
### Descriptive summary
Values entered/selected in the Genre field in the resource description form get converted to lowercase upon submission, e.g.:
![image](https://user-images.githubusercontent.com/14880206/64655752-64e44400-d3ea-11e9-9aab-34deef1cd088.png)
https://era-av.library.ualberta.ca/media_objects/5d86p118r

### Expected behavior
Values in this field remain in title case/comply with validation rules

### Actual behavior
Values get converted to lowercase upon submission of the resource description form

### Steps to reproduce the behavior

1. Create an item
2. Select any genre term (e.g. Music)
3. View the error on the record page

### Related work
#545

**Comment by jefferya** [comment]
Background:

Genre dropdown and validation against PBcore added by UAL via <https://github.com/ualbertalib/avalon/pull/302>. Modelled after `language` however `genre` appears to pass to the view the id whereas `language` passes a map with uri and text.

**Comment by jefferya** [comment]
@anayram Can you confirm the following MODS snippet for genre if a user specifies `Interview` as the genre in the resource description form?

```
<genre authority="pbcore" valueURI="http://pbcore.org/vocabularies/pbcoreGenre%23interview">Interview</genre>
```

For reference, the past looked like the following (notice the lowercase `i` and no uri)
```
<genre>interview</genre>
```

**Comment by jefferya** [comment]
Todo: add test to verify MODS created correctly for genre:
https://github.com/ualbertalib/avalon/blob/master/spec/models/media_object_spec.rb

**Comment by anayram** [comment]
Thanks @jefferya 

Yes, that is the correct URI:
http://pbcore.org/vocabularies/pbcoreGenre#interview
This property has a _hash URI_ but I believe the hash character encoding you have is correct by replaceing with %23

**Comment by jefferya** [comment]
Thank you @anayram. 

The `%23` appears to be included in the pbcore genre CVS file <https://github.com/ualbertalib/avalon/blob/avalon-6/config/pbcore_genre.csv>

This `%231` file was used in both ERA A+V 5 (previous version) and version 6 (current production). 

Not sure how to clean up the existing `%23` data. 

To make certain I correctly understand, the result should look like the following:

`<genre authority="pbcore" valueURI="http://pbcore.org/vocabularies/pbcoreGenre#interview">Interview</genre>`

**Comment by anayram** [comment]
Thank you @jefferya,

> To make certain I correctly understand, the result should look like the following:
> 
> `<genre authority="pbcore" valueURI="http://pbcore.org/vocabularies/pbcoreGenre#interview">Interview</genre>`

Yes, that is my understanding, the URI should use the `#` character. I don't know the story behind the use of `%23`. PBCore URIs are inconsistently represented in their documentation and I don't know to what extent this vocabulary is maintained but I added a follow up to [a related issue](https://github.com/WGBH/PBCore2.0/issues/59) in their GitHub repository 

For now we can use hashed URI if it seems feasible to you. Otherwise we can leave as is and revise when we have more information. Would that work on your side?

**Comment by jefferya** [comment]
Thank you @anayram for inquiring with the PBCore group.

> For now we can use hashed URI if it seems feasible to you. Otherwise we can leave as is and revise when we have more information. Would that work on your side?

Some thoughts about the options.

From the context of Avalon, it doesn't use the `valueURI` genre attribute beyond recording the uri. The genre element text is used for display/facet/etc. A UAL customization added the valueURI as part genre authority and validation work. Therefore either the # or %23 option is feasible.

Which is best for the future, # or %23?

One option, if we switch to the # format in the code then we end up with a mixture of %23 (in existing resources) and # (in new resources) unless clean-up is done to fix the existing MODS records. From the Avalon view point, a mixture doesn't appear to cause breakage. From the metadata side, I'm unsure the impact on usage and practice. Would a mixture of %23 and # cause issues from the metadata viewpoint (i.e., clean-up later)? Or should a clean-up be done sooner than later?

The other option, since the existing metadata is in the %23 format, we could continue, at least until more information is available (i.e., response from the PBCore group). However, if this approach adds work to the metadata group or others consuming the metadata then I'm unsure.

**Comment by anayram** [comment]
Thank you @jefferya ! Considering all options I think it would be preferable to keep using %23 for now, in the meantime we get more information.

From the point of view of W3C URI recommendations, using # would be better, but I'd like to avoid any inconsistencies for now. I will create a ticket for future cleanup and coordinate with you whenever it is a good moment to clean these URIs across the repository and your code.

Does that sound ok from your side? Thank you!

**Comment by jefferya** [comment]
@anayram Thank you. Sounds good to me.
