### ISSUE TITLE
Object edit should always go to Manage file(s) page

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#65]
### Expected behavior
PROD - Clicking on edit object from a record view should go to the first stage in the deposit workflow - Manage File(s)

### Actual behavior
Clicking on edit object from a record view goes to the Access Control page

### Steps to reproduce the behavior

1. Go to any object and click edit

**Comment by cwant** [comment]
Just testing a bit and looking at the code. The logic is that the 'Edit' button takes you to the first edit page for which 'Save' or 'Save and Continue' wasn't pressed (e.g., if you press 'Upload' but don't press 'Save and Continue', the 'Edit' button will take you to the upload page rather than the 'Access Control' page. Since the 'Access Control' page is the final step of the deposit workflow, that's where the 'Edit' button takes you when you click it.

This is useful behaviour to preserve, except for when all of the workflow steps are done, so I'll try to update only that case.

Here's a question though (and I do ask this since I don't manage any production collections): what would be more likely in need of updating: the files for the item in the repository, or the metadata? (My gut says the metadata, but I'm not a collection manager.)

**Comment by seanluyk** [comment]
Good point, Chris, I think metadata is much more likely to be updated than the files. From our user testing, a consistent issue that came up was confusion over the workflow. For example, one task asked users to edit metadata for an item and they were always confused why they were directed to the access control step. The consensus between @umarqasim @sfbetz at the time was that it's best for the workflow to be consistent (i.e. returning to edit mode starts and finishes at a consistent place).  Let's talk this one through more at a grooming meeting

**Comment by seanluyk** [comment]
Doing some cleanup
